version: '3.7'

services:
  psql:
    container_name: psql_server
    image: postgres:16.1
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5432:5432"

# --------BACKEND_SERVICE--------
  gateway:
    container_name: backend_gateway
    image: vm-control/gateway
    ports:
      - "8080:8080"
    networks:
      - vm-control

  user-service:
    container_name: user-service
    image: vm-control/user-service
    networks:
      - vm-control

  ssh-service:
    container_name: ssh-service
    image: vm-control/ssh-service
    networks:
      - vm-control
# -------------------------------

networks:
  vm-control:
    driver: bridge